######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 18 17:08:32 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h screen.h snake.h
SOURCES += main.cpp mainwindow.cpp screen.cpp snake.cpp
