#############################################################################
# Makefile for building: arm_snake
# Generated by qmake (2.01a) (Qt 4.7.3) on: ?? 6? 18 17:08:38 2019
# Project:  arm_snake.pro
# Template: app
# Command: /home/Qt/qt4.7.3-arm/bin/qmake-arm -o Makefile arm_snake.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-none-linux-gnueabi-gcc -lts
CXX           = arm-none-linux-gnueabi-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../Qt/qt4.7.3-arm/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I../../Qt/qt4.7.3-arm/include/QtCore -I../../Qt/qt4.7.3-arm/include/QtNetwork -I../../Qt/qt4.7.3-arm/include/QtGui -I../../Qt/qt4.7.3-arm/include -I. -I. -I../../Qt/qt4.7.3-arm/tslib/include
LINK          = arm-none-linux-gnueabi-g++ -lts
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/Qt/qt4.7.3-arm/lib
LIBS          = $(SUBLIBS)  -L/home/Qt/qt4.7.3-arm/tslib/lib -L/home/Qt/qt4.7.3-arm/lib -lQtGui -L/home/Qt/qt4.7.3-arm/tslib/lib -L/home/Qt/qt4.7.3-arm/lib -lQtNetwork -lQtCore -lrt -lpthread 
AR            = arm-none-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /home/Qt/qt4.7.3-arm/bin/qmake-arm
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-none-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		screen.cpp \
		snake.cpp moc_mainwindow.cpp \
		moc_screen.cpp
OBJECTS       = main.o \
		mainwindow.o \
		screen.o \
		snake.o \
		moc_mainwindow.o \
		moc_screen.o
DIST          = ../../Qt/qt4.7.3-arm/mkspecs/common/g++.conf \
		../../Qt/qt4.7.3-arm/mkspecs/common/unix.conf \
		../../Qt/qt4.7.3-arm/mkspecs/common/linux.conf \
		../../Qt/qt4.7.3-arm/mkspecs/common/qws.conf \
		../../Qt/qt4.7.3-arm/mkspecs/qconfig.pri \
		../../Qt/qt4.7.3-arm/mkspecs/features/qt_functions.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/qt_config.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/exclusive_builds.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/default_pre.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/release.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/default_post.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/warn_on.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/qt.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/unix/thread.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/moc.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/resources.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/uic.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/yacc.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/lex.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/include_source_dir.prf \
		arm_snake.pro
QMAKE_TARGET  = arm_snake
DESTDIR       = 
TARGET        = arm_snake

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: arm_snake.pro  ../../Qt/qt4.7.3-arm/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf ../../Qt/qt4.7.3-arm/mkspecs/common/g++.conf \
		../../Qt/qt4.7.3-arm/mkspecs/common/unix.conf \
		../../Qt/qt4.7.3-arm/mkspecs/common/linux.conf \
		../../Qt/qt4.7.3-arm/mkspecs/common/qws.conf \
		../../Qt/qt4.7.3-arm/mkspecs/qconfig.pri \
		../../Qt/qt4.7.3-arm/mkspecs/features/qt_functions.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/qt_config.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/exclusive_builds.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/default_pre.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/release.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/default_post.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/warn_on.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/qt.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/unix/thread.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/moc.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/resources.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/uic.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/yacc.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/lex.prf \
		../../Qt/qt4.7.3-arm/mkspecs/features/include_source_dir.prf \
		/home/Qt/qt4.7.3-arm/lib/libQtGui.prl \
		/home/Qt/qt4.7.3-arm/lib/libQtNetwork.prl \
		/home/Qt/qt4.7.3-arm/lib/libQtCore.prl
	$(QMAKE) -o Makefile arm_snake.pro
../../Qt/qt4.7.3-arm/mkspecs/common/g++.conf:
../../Qt/qt4.7.3-arm/mkspecs/common/unix.conf:
../../Qt/qt4.7.3-arm/mkspecs/common/linux.conf:
../../Qt/qt4.7.3-arm/mkspecs/common/qws.conf:
../../Qt/qt4.7.3-arm/mkspecs/qconfig.pri:
../../Qt/qt4.7.3-arm/mkspecs/features/qt_functions.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/qt_config.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/exclusive_builds.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/default_pre.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/release.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/default_post.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/warn_on.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/qt.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/unix/thread.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/moc.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/resources.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/uic.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/yacc.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/lex.prf:
../../Qt/qt4.7.3-arm/mkspecs/features/include_source_dir.prf:
/home/Qt/qt4.7.3-arm/lib/libQtGui.prl:
/home/Qt/qt4.7.3-arm/lib/libQtNetwork.prl:
/home/Qt/qt4.7.3-arm/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile arm_snake.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/arm_snake1.0.0 || $(MKDIR) .tmp/arm_snake1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/arm_snake1.0.0/ && $(COPY_FILE) --parents mainwindow.h screen.h snake.h .tmp/arm_snake1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp screen.cpp snake.cpp .tmp/arm_snake1.0.0/ && (cd `dirname .tmp/arm_snake1.0.0` && $(TAR) arm_snake1.0.0.tar arm_snake1.0.0 && $(COMPRESS) arm_snake1.0.0.tar) && $(MOVE) `dirname .tmp/arm_snake1.0.0`/arm_snake1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/arm_snake1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_screen.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_screen.cpp
moc_mainwindow.cpp: screen.h \
		snake.h \
		mainwindow.h
	/home/Qt/qt4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_screen.cpp: snake.h \
		screen.h
	/home/Qt/qt4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) screen.h -o moc_screen.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		screen.h \
		snake.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		screen.h \
		snake.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

screen.o: screen.cpp screen.h \
		snake.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o screen.o screen.cpp

snake.o: snake.cpp snake.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snake.o snake.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_screen.o: moc_screen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_screen.o moc_screen.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

